#Array Fundamental:

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
print(a)

[1 2 3 4 5]


Elements of an array can be accessed in various ways. For instance, we can access an individual element of this array as we would access an element in the original list: using the integer index of the element within square brackets.

In [4]:
a[0]

1

Like the original list, the array is mutable.

In [5]:
a[0]=15
print(a)

[15  2  3  4  5]


Also like the original list, Python slice notation can be used for indexing.

In [6]:
a[:3]

array([15,  2,  3])

In [7]:
a[2:]

array([3, 4, 5])

One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [8]:
b=a[2:]
b[0]=20
print(a)

[15  2 20  4  5]
